set  -g default-terminal "screen-256color"
set  -g base-index      0
set  -g status-keys vi
set  -g mode-keys   vi
set  -s escape-time       0
set  -g history-limit     2000
setw -g aggressive-resize off
setw -g pane-base-index 0
setw -g clock-mode-style  12

bind -T copy-mode u send -X page-up
bind -T copy-mode f send -X page-down
bind u copy-mode -u

set-option -g prefix C-Space
set-option -g prefix2 C-b

# Inlined from tmux-sensible (https://github.com/tmux-plugins/tmux-sensible)
set -g display-time 4000
set -g status-interval 5
set -g focus-events on
bind C-p previous-window
bind C-n next-window
bind R source-file '~/.tmux.conf'

bind-key -n M-h select-pane -L
bind-key -n M-l select-pane -R
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U

# ============================================= #

set -g mouse on
