#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.10"
# dependencies = ["openai", "imageio-ffmpeg"]
# ///
"""Transcribe a downloaded cooking video to text with timestamps.

Two paths, in order of preference:
  1. Subtitles (srt) downloaded alongside the video — perfect text, free.
     Skipped if you pass --force-api, or if the srt turns out to be
     autogenerated music-lyrics garbage and the agent decides to override.
  2. OpenAI gpt-transcribe on the extracted audio — high-quality ASR that
     handles music-under-voiceover well (recipes reels often have both).

Usage:
    uv run scripts/transcribe.py \
        --video <path> --source <path/to/source.json> --outdir <dir>

Options:
    --video PATH        Path to the downloaded video file.
    --source PATH       Path to source.json (for subtitle paths).
    --outdir DIR        Where to write transcript.json / transcript.txt.
    --force-api         Always use the audio API, even if subtitles exist.
    --lang LANG         Optional language hint for gpt-transcribe (e.g. "en").

Writes:
    transcript.json     {"segments": [{"start": s, "end": s, "text": "..."}]}
    transcript.txt      Plain text, one line per segment.
"""
import argparse
import json
import os
import subprocess
import sys
import tempfile

import imageio_ffmpeg

FFMPEG = imageio_ffmpeg.get_ffmpeg_exe()


def parse_srt(path: str) -> list[dict]:
    """Parse an srt file into [{"start": float, "end": float, "text": str}]."""
    segments = []
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    i = 0
    while i < len(lines):
        if "-->" in lines[i]:
            start_s, end_s = lines[i].split("-->")
            def ts(s):
                h, m, rest = s.strip().split(":")
                sec, ms = rest.split(",")
                return int(h) * 3600 + int(m) * 60 + int(sec) + int(ms) / 1000
            text = []
            i += 1
            while i < len(lines) and lines[i].strip():
                text.append(lines[i].strip())
                i += 1
            segments.append({"start": ts(start_s), "end": ts(end_s),
                             "text": " ".join(text)})
        i += 1
    return segments


def pick_subtitle(source: dict) -> str | None:
    """Return the best srt path from source.json, preferring non-auto subs."""
    paths = source.get("subtitle_paths") or []
    if not paths:
        return None
    base = (source.get("video_path") or "").rsplit(os.sep, 1)[-1]
    stem = base.split(".")[0] if "." in base else base
    regular, auto = [], []
    for p in paths:
        (auto if "auto" in p else regular).append(p)
    return os.path.join(os.path.dirname(source.get("video_path") or "."), (regular or auto)[0])


def extract_audio(video: str, wav: str) -> None:
    subprocess.run(
        [FFMPEG, "-y", "-i", video, "-vn", "-ac", "1", "-ar", "16000", wav],
        check=True, capture_output=True,
    )


def transcribe_api(wav: str, lang: str | None, model: str) -> list[dict]:
    from openai import OpenAI
    client = OpenAI()
    with open(wav, "rb") as f:
        kwargs = dict(model=model, file=f, response_format="json")
        if lang:
            kwargs["language"] = lang
        result = client.audio.transcriptions.create(**kwargs)
    # gpt-transcribe accepts 'json' (segmented when available) or 'text'.
    segments = getattr(result, "segments", None)
    if segments:
        return [{"start": s.get("start", 0), "end": s.get("end", 0),
                 "text": s.get("text", "").strip()}
                for s in segments if s.get("text", "").strip()]
    text = getattr(result, "text", "").strip()
    return [{"start": 0, "end": 0, "text": text}] if text else []


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--video", required=True)
    ap.add_argument("--source", required=True)
    ap.add_argument("--outdir", default="work")
    ap.add_argument("--force-api", action="store_true")
    ap.add_argument("--model", default="gpt-transcribe",
                    help="transcription model (default gpt-transcribe)")
    ap.add_argument("--lang")
    args = ap.parse_args()

    import os as _os
    if not _os.environ.get("OPENAI_API_KEY"):
        print("ERROR: OPENAI_API_KEY is not set — needed for transcription when "
              "no subtitles exist.", file=sys.stderr)
        return 2

    os.makedirs(args.outdir, exist_ok=True)
    with open(args.source) as f:
        source = json.load(f)

    segments = []
    used = "subtitles"
    if not args.force_api:
        sub = pick_subtitle(source)
        if sub and os.path.exists(sub):
            segments = parse_srt(sub)
            print(f"using subtitles: {sub}", file=sys.stderr)
    if not segments:
        used = "gpt-transcribe"
        with tempfile.TemporaryDirectory() as tmp:
            wav = os.path.join(tmp, "audio.wav")
            extract_audio(args.video, wav)
            size_mb = os.path.getsize(wav) / (1024 * 1024)
            if size_mb > 25:
                print(f"ERROR: extracted audio is {size_mb:.1f}MB, above the "
                      f"25MB API limit — video too long to transcribe in one "
                      f"call.", file=sys.stderr)
                return 2
            segments = transcribe_api(wav, args.lang, args.model)
    # absorb very short segments into neighbors for a cleaner transcript
    merged = []
    for seg in segments:
        if merged and seg["end"] - merged[-1]["end"] < 0.6 and len(seg["text"]) < 3:
            merged[-1]["end"] = seg["end"]
            merged[-1]["text"] += " " + seg["text"]
        else:
            merged.append(dict(seg))

    with open(os.path.join(args.outdir, "transcript.json"), "w") as f:
        json.dump({"used": used, "segments": merged}, f, indent=2)
    with open(os.path.join(args.outdir, "transcript.txt"), "w") as f:
        for seg in merged:
            f.write(f"[{seg['start']:.1f}-{seg['end']:.1f}] {seg['text']}\n")

    print(json.dumps({"used": used, "segment_count": len(merged)}, indent=2))
    if not merged:
        print("WARNING: transcript is empty — the video may have no narration "
              "(music-only reel). on-screen text may be the only signal.",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())